// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxenowjlyyupnfgpmekl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4ZW5vd2pseXl1cG5mZ3BtZWtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNjAyMTAsImV4cCI6MjA2MDgzNjIxMH0.aO4xgpBl0XZaQQeAwZWQBFFgJeQtHknXBy6_XeHgifw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);